spring.datasource.url=jdbc:postgresql://localhost:5432/invigilation_db
spring.datasource.username=postgres
spring.datasource.password=2807

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
# EMAIL1.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=invigoadm@gmail.com
spring.mail.password=qzosavvisjktdjdc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# TWILIO WHATSAPP
twilio.account.sid=YOUR_SID
twilio.auth.token=YOUR_TOKEN